### ISSUE TITLE
ImageCard-Weather doesn't load. Cannot read properties of undefined

### ISSUE THREAD

**Issue by jesegher** [pnp/sp-dev-fx-aces#102]
Sample: ImageCard-Weather

Author: @aakashbhardwaj619

Expected behavior: Load the ACE card and property pane associated with it

Observed behavior: Technical error: Cannot read properties from undefined. See printscreen

<img width="676" alt="image" src="https://user-images.githubusercontent.com/54183944/196756003-b4c56120-cb42-46fc-ae25-d6562f793638.png">

Steps to reproduce:

- Ensure that you are at the solution folder
- In the command-line run:
- npm install
- gulp serve
- Browse to your hosted workbench https://yourtenant.sharepoint.com/sites/_layouts/15/workbench.aspx and add the adaptive card extension.
- add the local ACE card. 
- Observe error

OS: Windows 11
Target: M365 Viva Connections
Browser: Edge
Tooling: 
- VS Code with 
- SP Framework 1.15.2 
- Node.js 14.17.3 
- Gulp 2.3.0

**Comment by dcashpeterson** [comment]
@aakashbhardwaj619  is this something you can look into and see if you can assist?

**Comment by dcashpeterson** [comment]
@jesegher I merged a PR to fix the issue. The ACE should work now.
