### ISSUE TITLE
[ImageCard-my-recent-files]:[Tooltip for the file title and path of file]

### ISSUE THREAD

**Issue by PanchamiM** [pnp/sp-dev-fx-aces#103]
I want to use the tooltip property to textbox in adaptive card but that is not availble so I thought of using tooltip for Actions. But the Actions support tooltip only from 1.5 version. And SPFX viva connections and teams support 1.3 and 1.4 respectively. Please suggest on this.

**Comment by dcashpeterson** [comment]
@PanchamiM are you asking if you can use a tool tip on a text box or how to add a tool tip to the action on this particular sample quickview? The SelectAction doesn't support a tooltip in version 1.3. I would suggest using a text label and putting the content you want for the tool tip in there in either case. You can always revisit when the versions of the Adaptive Card Framework get updated in SPFx/

**Comment by dcashpeterson** [comment]
Closed and answered

**Comment by PanchamiM** [comment]
Is the text label can be used as hover as it works in tooltip?

**Comment by PanchamiM** [comment]
@dcashpeterson 
Is the text label can be used as hover as it works in tooltip?

**Comment by dcashpeterson** [comment]
@PanchamiM no. As you mentioned the tool tip functionality isn't available in version 1.3 so you would need to provide the data from the tooltip in the label on the screen. You could also use a button that opens a new card with the explanation but that feels like a bad experience for the user. What is it that you are trying to show in a tool tip that can't be in text on the screen?

**Comment by PanchamiM** [comment]
@dcashpeterson we are showing name of the recent files, as it is very long we are truncating it. So, it will be easier for user if the hover property is there where we can show the entire file name.

**Comment by dcashpeterson** [comment]
I think that is not a great user experience as many files could have a similar root name before things are truncated and requiring the user to hover over something to get the tool tip will not be a useful experience. Your options are either to make the text clickable and navigate to a new Quick View with the full name of the file on that card and a back arrow that would bring the user to the previous list or put the entire file name on the screen with a label. Sorry I don't have a better answer.

**Comment by PanchamiM** [comment]
@dcashpeterson Thank you for your help
