### ISSUE TITLE
[PrimaryTextCard-my-calendar-plan]:[Suddenly in our dev and test environment the card view is not showing the formatted text and image]

### ISSUE THREAD

**Issue by PanchamiM** [pnp/sp-dev-fx-aces#111]
Suudenly from today the card view from the solution which has markdown to format text is showing just plain text. Can anyone has any idea why is this happening. In other test and prod environments it is working fine.

**Comment by PanchamiM** [comment]
![Calendar](https://user-images.githubusercontent.com/117371226/206669743-bf7a01aa-f1d9-482a-af3a-3abeec754057.PNG)

**Comment by PanchamiM** [comment]
From 9th Dec 2022 onwards in our test environment also the card view is not working. It is being displayed as shown in above image.

**Comment by dcashpeterson** [comment]
@PanchamiM Thanks for sharing this. To help triage it would help if you could give us some additional information. Is this on your SharePoint home site in the browser or Teams (web or browser or mobile). What version of SPFx are you using?

**Comment by PanchamiM** [comment]
@dcashpeterson Below are the details
Yes, the cards are placed in sharepoint home site and also the issue is in teams(web/browser)
SPFX Version - 1.13

**Comment by dcashpeterson** [comment]
Thanks for the update. @joaojmendes do you have some time to look at this issue?

**Comment by joaojmendes** [comment]
@PanchamiM the Markdown is not supported in teams or in Viva Connection in Teams App (mobile)

**Comment by PanchamiM** [comment]
@joaojmendes Last week till monday the markdown was working fine in Teams Viva Connection. Now it stopped working in both teams and Browser. This issue is happening in dev and test environment.
SPFX Version - 1.13
Non Working environment - Dev and test
Non Working host - SharePoint home page(tested in desktop browser), Teams Viva connection

**Comment by joaojmendes** [comment]
I never got this work on viva connections I know that we have some problems with markdown on teams app.

Here on picture on my mobile .  The solution is remove the markdow from cardview.

Thanks!

________________________________
De: PanchamiM ***@***.***>
Enviado: segunda-feira, dezembro 12, 2022 5:00 AM
Para: pnp/sp-dev-fx-aces ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-aces] [PrimaryTextCard-my-calendar-plan]:[Suddenly in our dev and test environment the card view is not showing the formatted text and image] (Issue #111)


@joaojmendes<https://github.com/joaojmendes> Last week till monday the markdown was working fine in Teams Viva Connection. Now it stopped working in both teams and Browser. This issue is happening in dev and test environment.
SPFX Version - 1.13
Non Working environment - Dev and test
Non Working host - SharePoint home page(tested in desktop browser), Teams Viva connection

**Comment by PanchamiM** [comment]
@joaojmendes If we remove markdown we will not get the desired UI output. Is there any way to achieve the UI for card view as shown in sample.

**Comment by joaojmendes** [comment]
No, at this moment .


From: PanchamiM ***@***.***>
Date: Monday, 12 December 2022 at 11:29
To: pnp/sp-dev-fx-aces ***@***.***>
Cc: João Mendes ***@***.***>, Mention ***@***.***>
Subject: Re: [pnp/sp-dev-fx-aces] [PrimaryTextCard-my-calendar-plan]:[Suddenly in our dev and test environment the card view is not showing the formatted text and image] (Issue #111)

@joaojmendes<https://github.com/joaojmendes> If we remove markdown we will not get the desired UI output. Is there any way to achieve the UI for card view as shown in sample.

**Comment by PanchamiM** [comment]
Any alternative solution for this issue.

**Comment by PanchamiM** [comment]
Then will this solution will be removed from github as it is not working with markdown.

**Comment by dcashpeterson** [comment]
@joaojmendes the markdown doesn't work but the sample is valid for the references to the calendar APIs. How do you feel about me adding a note at the top about the markdown. This is a recent change as I know this worked when I approved the PR in the first place.

**Comment by joaojmendes** [comment]
Hi Derek,

For me is ok, make sense. I will change it .

Thank you.
João

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Derek Cash-Peterson ***@***.***>
Enviado: Friday, December 16, 2022 11:36:54 AM
Para: pnp/sp-dev-fx-aces ***@***.***>
Cc: João Mendes ***@***.***>; Mention ***@***.***>
Assunto: Re: [pnp/sp-dev-fx-aces] [PrimaryTextCard-my-calendar-plan]:[Suddenly in our dev and test environment the card view is not showing the formatted text and image] (Issue #111)


@joaojmendes<https://github.com/joaojmendes> the markdown doesn't work but the sample is valid for the references to the calendar APIs. How do you feel about me adding a note at the top about the markdown. This is a recent change as I know this worked when I approved the PR in the first place.

**Comment by dcashpeterson** [comment]
@joaojmendes I added a note to the PR while I was merging a few other things so I am going to close this. Feel free to submit a PR if you want to edit what I did.
