### ISSUE TITLE
input File

### ISSUE THREAD

**Issue by matthieu6010** [pnp/sp-dev-fx-aces#113]
Hi,

Is there a way to sendfile with an input type File ?

Thank you for your answer.
Sincerely, 

Matthieu

**Comment by dcashpeterson** [comment]
@matthieu6010 there isn't a file upload element in the adaptive card framework so you can't add an input form field. Depending on what type of tile you are looking to add you can use the new VivaAction.SelectMedia. This allows you to use the native file picker to upload a file and then in your onAction method you can handle that file and push it where you like. I hope that helps
