### ISSUE TITLE
ImageCard-Weather: ERROR: WeatherAdaptiveCardExtension is not initialized

### ISSUE THREAD

**Issue by samveilleux** [pnp/sp-dev-fx-aces#138]
## Sample
ImageCard-Weather

## Authors
@aakash_316

## Expected or Desired Behavior
ACE should render after saving properties

## Observed Behavior
<img width="503" alt="image" src="https://user-images.githubusercontent.com/25227487/234924106-d14838b7-08a0-496a-a1b5-89b5d96e0e85.png">

## Steps to Reproduce
- Package and Deploy Solution to App Catalog
- Add Weather Ace to Viva Connections Dashboard
- Set Properties including image url, location, Bing and Azure API keys
- Weather Ace renders
- Save changes to dashboard
- Weather ACE throws above error

# Environment Details (*Development & Target environment*)
OS: Windows 11
Target: M365 Viva Connections
Browser: Edge
Tooling:

VS Code with
SP Framework 1.15.2
Node.js v16.20.0
Gulp 2.3.0

**Comment by dcashpeterson** [comment]
@aakashbhardwaj619 Can you please take a look at this and see what the issue might be?
