### ISSUE TITLE
PrimaryTextCard-Graph-UnreadEmails: Error Gulp Serve

### ISSUE THREAD

**Issue by aidab98** [pnp/sp-dev-fx-aces#143]
Whenever I run the command gulp serve, I get the Error: Cannot find module '@microsoft/sp-build-web'.
I have all the prerequisites of SharePoint Framework installed.

Please help and thank you!

**Comment by a1mery** [comment]
Did you successfully run `npm install` ?

Which version of Node are you using ?

**Comment by aidab98** [comment]
Node version v16.17.0

**Comment by aidab98** [comment]
Thank you @a1mery  so much for your help! I installed Node v14 and it works now.
