### ISSUE TITLE
PRIMARYTEXTCARD-MYEMAILS - Missing Manifest

### ISSUE THREAD

**Issue by aidab98** [pnp/sp-dev-fx-aces#144]
## Authors

@dcashpeterson 

## Question

'm running gulp serve on this code and I receive an error that there is a missing file in the folder. 
Specifically this file: C:\Viva-ACE-Samples\sp-dev-fx-aces\samples\PrimaryTextCard-MyEmails\src\adaptiveCardExtensions\myEmails\MyEmailsAdaptiveCardExtension.manifest.json

The manifest.json in the src file is missing unlike in other samples.

![image](https://github.com/pnp/sp-dev-fx-aces/assets/86289425/b308c8c2-c706-4393-bd3e-9616a78b7f34)
![image](https://github.com/pnp/sp-dev-fx-aces/assets/86289425/0fd6e257-3343-4222-b981-d579c64e162b)

**Comment by a1mery** [comment]
The manifest was not in the correct folder. I've created a PR to solve this issue.
In the meantime you can move it yourself locally (the manifest file is in the quickView folder).
