### ISSUE TITLE
 TSLint is not supported for rush-stack-compiler-4.X packages.

### ISSUE THREAD

**Issue by MatteoChiaffitella** [pnp/sp-dev-fx-aces#147]
When I run "gulp bundle --ship" comand I have this error:
TSLint is not supported for rush-stack-compiler-4.X packages.

So I uninstall the 4.5 package and install the 3.9 one, but when I run "gulp bundle --ship" it take this error:
'Cannot find module '@microsoft/rush-stack-compiler-4.5'

How can I solve it?

**Comment by dcashpeterson** [comment]
@MatteoChiaffitella is this related to a specific sample? If it is please provide more details as to which sample you are referring to. It looks like you have the wrong version of React installed for the sample you are working with. Some work with older versions, some work with newer versions. If this is a general SPFx development related question, you might get a better response by posting here [SP-Dev-Docs](https://github.com/SharePoint/sp-dev-docs)

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If this is still an issue please create a new issue and reference this one with the requested information.
