### ISSUE TITLE
[PrimaryTextCard-my-calendar-plan]::Number of Events is wrong in Mobile

### ISSUE THREAD

**Issue by arunakshi** [pnp/sp-dev-fx-aces#176]
The number of events in myCalendar card is not correct and we always see that there are no events in mobile devices. 
We tested this in IPhone 14 Pro, IPhone SE devices and same issue occur in both devices. 

Please refer to the screenshot below: 
![image](https://github.com/pnp/sp-dev-fx-aces/assets/12812202/78e17a56-eace-4ffb-90bb-27767d2df28c)

**Comment by arunakshi** [comment]
@dcashpeterson, Thanks for quick reply. Is there plans for upgrading this card to support in mobile devices?

**Comment by dcashpeterson** [comment]
@arunakshi these are all community samples. There is no plan to update this sample on my end but if someone in the community would like to update it I will gladly review the PR.

**Comment by dcashpeterson** [comment]
@joaojmendes of you are interested there is a request to update your sample.
