### ISSUE TITLE
ImageCard-ApplyLeave-OOF-Holiday sample is missing source code folder, readme.md and possibly other @artifacts?

### ISSUE THREAD

**Issue by alexabramkin** [pnp/sp-dev-fx-aces#191]
## Sample (which sample are you talking about)
ImageCard-ApplyLeave-OOF-Holiday

## Authors
@dcashpeterson 

## Question
ImageCard-ApplyLeave-OOF-Holiday sample is missing source code folder, readme.md and possibly other  @artifacts?
![image](https://github.com/user-attachments/assets/342fef87-e26f-4cec-91c3-22751e3dca1d)

**Comment by alexabramkin** [comment]
@dcashpeterson this is the one I have mentioned to you at the Collab Days NE couple of weeks ago.

**Comment by dcashpeterson** [comment]
@alexabramkin Thanks for brining this to my attention. It looks like this sample was partially published by mistake. This PR was not approved so we don't have the source code for it. We will be deleting this sample. Is there something specific your looking for? I can try to point you to a different sample.

**Comment by alexabramkin** [comment]
Thank you for your reply. Functionality sounded interesting (judged by the name), just wanted to take a closer look at the implementation as an inspiration for something with similar functional requirements we might build internally.
