### ISSUE TITLE
Contributing guidelines to this repository needs to be polished for naming conventions...

### ISSUE THREAD

**Issue by siddharth-vaghasia** [pnp/sp-dev-fx-aces#22]
I recently contributed to this repo and found a few changes that might be required to contribute guidelines as it is referring to content based on spfx web part sample gallery..

https://github.com/pnp/sp-dev-fx-aces/blob/b3f970681671836f2a032854e376bc090b496d8e/.github/CONTRIBUTING.md

More specifically it require changes to below section

![image](https://user-images.githubusercontent.com/9557557/147917126-094f38f5-0e01-4826-a791-ec7e2d2cd2b1.png)

Happy to help if I can update this but might need actual naming and structuring guidelines 

Also, the contribution guidance link is broken at root readme file of this repo

https://github.com/pnp/sp-dev-fx-aces/blob/main/README.md

![image](https://user-images.githubusercontent.com/9557557/147917287-0773afcb-0191-4a6d-a244-7542793d10ee.png)

**Comment by dcashpeterson** [comment]
@siddharth-vaghasia I created a new contributions guidelines for this repo and made the updates. Thanks for the catch.
