### ISSUE TITLE
HybridWork- Checkin issue with close button Mobile Device 

### ISSUE THREAD

**Issue by ahmedmahmoudR** [pnp/sp-dev-fx-aces#35]
I have new  issue with HybridWork-Checkin Card when I click close button after submit new request nothing happen from mobile teams , 
 close button work well when I use it from Teams Desktop but doesn't work with iPhone

![This is an image](https://i.imgur.com/IKiSjVw.jpg)

**Comment by ahmedmahmoudR** [comment]
@ArijitCloud  

any advice would be appreciated

**Comment by ArijitCloud** [comment]
@ahmedmahmoudR Thanks for testing this out. Theoretically there is no separate configuration for mobile device that is exposed by SPFx, and so whatever works in desktop should work in mobile as well with minor limitations mentioned here,
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/known-issues-adaptive-cards

Unfortunately I don't own any apple device to test it out if something specific is broken in app or SPFx. As an alternate option, try this out, 
replace `this.quickViewNavigator.push`  in QuickView.ts with `this.quickViewNavigator.replace `
this will give a close button from the view without needing a separate close button.

**Comment by ahmedmahmoudR** [comment]
@ArijitCloud Thanks for your support,

issue has been solved when I change if condation `CheckinCompleteView.ts`  

` public onAction(action: IActionArguments | any): void {
        if(true){  // change this to true 
            this.quickViewNavigator.close();
        }
    }`

I Don't know what happen to `action.id`  when I open card from mobile device but I don't think its return the right id from Json value

**Comment by ArijitCloud** [comment]
That should be fine, as that's the only action button in that quickview. But it's strange why id should not be available. Can you try some other sample/create a hello world and test inside your ios mobile device? If the issue persists, consider opening issue in SPFx repo.

**Comment by anoopt** [comment]
@ahmedmahmoudR - please find the related issue and the solution [here](https://github.com/SharePoint/sp-dev-docs/issues/7671#issuecomment-1023103502) .

**Comment by dcashpeterson** [comment]
answered and closing.
