### ISSUE TITLE
External link not opening using the inbuilt browser like in viva connections mobile app

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/sp-dev-fx-aces#37]
Hi,
I have a viva connection app, which has external links. When i click on the link, it opens outside i.e it opens in the mobile phones default browser. where as if we create a normal web part, it opens in the inbuilt browser

**Comment by PopWarner** [comment]
Hi @harshdamaniahd, hope you are doing well. 

Are you referring to a sample in the repo or a custom ACE you developed? 

Thanks in advance. 😊

**Comment by harshdamaniahd** [comment]
@PopWarner Thanks :-) that was superquick. I have created my own sample.

**Comment by PopWarner** [comment]
Awesomeness thanks! We will try to look into it as soon as possible. I know there were some issues with that in preview. 

Additionally, you can check the dedicated SPFx issues list in the sp-dev-docs repo to see if there are any reported solutions:

http://aka.ms/spfx-issues

That repo is more dedicated for SPFx related issues and questions overall.

**Comment by harshdamaniahd** [comment]
@PopWarner 
Thank you :-) , was not sure where to raise such kind of issue.
I have an adaptive card that displays job links, i wish when user clicks on the link, it opens in the same frame inside the app. 
like this it works for web links 
![image](https://user-images.githubusercontent.com/11780473/153767143-0852b89d-6b56-4f61-8a76-5112c661d534.png)

This works for web links, but if we have links on quick view it doesnt

`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.OpenUrl",
                    "title": "Action.OpenUrl",
                    "url": "https://adaptivecards.io/"
                }
            ]
        },
        {
            "type": "TextBlock",
            "text": "Check out [Adaptive Cards](https://adaptivecards.io)",
            "wrap": true
        }
    ]
}`

**Comment by dcashpeterson** [comment]
closing. Was reported to SP Dev Docs.
