### ISSUE TITLE
PrimaryTextCard-Covid-Indicator doesn't work on mobile iOS/Android

### ISSUE THREAD

**Issue by Mikhail2k15** [pnp/sp-dev-fx-aces#43]
Looks like the tables, images in the markdown are not supported on mobile in card view.
![image](https://user-images.githubusercontent.com/11201670/154841858-245aa860-b73f-49b2-8573-0d11c0edd791.png)

https://github.com/pnp/sp-dev-fx-aces/blob/64c0313f8492532f846f7a3556dc9848c4fdff0e/samples/PrimaryTextCard-Covid-Indicator/src/cards/cardView/CardView.ts#L18

The heading markdown tag doesn't render properly on iOS Quick View. 
Expected 
![image](https://user-images.githubusercontent.com/11201670/154844202-9da86b10-f294-4c5f-a511-b3ec751ccbd3.png)
ios you can see ### before date and strange orange color
![image](https://user-images.githubusercontent.com/11201670/154844222-5c06d30f-37a4-41f0-bc21-16d4f170cc0a.png)

**Comment by dcashpeterson** [comment]
@joaojmendes Looping you in. I know there are some issues with mobile device support. Is there anything you can do here to assist?

**Comment by joaojmendes** [comment]
Hi , I tested on my IOS in SharePoint App and Browser Safari and everything is working 
![IMG_6695](https://user-images.githubusercontent.com/12551125/156813667-9681f04d-4573-4189-9fc4-2d5e09ceaee9.PNG)
![IMG_6696](https://user-images.githubusercontent.com/12551125/156813
![IMG_6694](https://user-images.githubusercontent.com/12551125/156813706-f2b550b1-6b46-4502-813f-424b403aae95.PNG)
687-afe46b8c-d1c3-4ddd-bd85-e0682677e4f3.PNG)
.

**Comment by Mikhail2k15** [comment]
Hi I'm not talking about **SharePoint App or Browser Safari**. It doesn't work for Teams App for ios inside Viva Connections App.
