### ISSUE TITLE
BasicCard-Graph-UpcomingEvents: Error in Teams viva connections app

### ISSUE THREAD

**Issue by jimmyalfSoleil** [pnp/sp-dev-fx-aces#54]
## Sample
> Which sample are you having trouble with? 
BasicCard-Graph-UpcomingEvents
PrimaryTextCard-Graph-UnreadEmails

They both works fine on a home site in SharePoint and Teams using a webbrowser.
But when I add the viva connections teams app I get the error:

"Unable to retrieve Client Secret" for BasicCard-Graph-UpcomingEvents and 
PrimaryTextCard-Graph-UnreadEmails just says "Loading..."

## Authors
[Nick Brown](https://github.com/techienickb) ([@techienickb](https://twitter.com/techienickb))
[Zach Roberts](https://github.com/zachroberts8668) ([@ZachSPODev](https://twitter.com/ZachSPODev))

## Expected or Desired Behavior
No errors in teams viva connection app. 

## Observed Behavior

> What does it do?
Throw an something went wrong error

## Steps to Reproduce
Add viva connection app in teams

# Environment Details (*Development & Target environment*)
Works in all browser but not in teams for windows and macOS. latest version of teams to this date.

**Comment by anoopt** [comment]
@jimmyalfSoleil - Do you see this issue in the Teams mobile app as well? Maybe the [thread here](https://github.com/SharePoint/sp-dev-docs/issues/7646) has some information that you might find useful.

**Comment by jimmyalfSoleil** [comment]
Yes, it's the samt error on mobile. Everything's works fine in our developer tenant though. Same issues as this https://github.com/SharePoint/sp-dev-docs/issues/7693

**Comment by techienickb** [comment]
> @techienickb @zachroberts8668 Can you please take a look at the related issues and see if there is anything we can do with your samples? Thanks, -Derek

When I tested my sample I didn't get this error in the teams mobile app.  I'm not using any custom api's so client secret shouldn't be a thing.  

@jimmyalfSoleil what version of the mobile teams app are you using?

Looks more like a configuration issue with Jimmy's tenant.

**Comment by jimmyalfSoleil** [comment]
@techienickb I’m using Sessions-ID:5220bafd-733c-47af-947a-7e6b19acf37b
Teams-version:1.077.2022063103
Appversion:0.2.202203100727-release-vcm-MarchT1
Användarring:general
SDK-version:0.9.6

Tenant have the config
accessTokenAcceptedVersion:1

**Comment by techienickb** [comment]
I can confirm that this error exists and it doesn't look to be isolated to this control, looks to be a wider SPFx issue.  I get the same issue with my UnreadEmails ACE.  Unable to access client secret.  

@VesaJuvonen I may need you to do some digging.  Mobile Teams app, SPFx's msGraphClientFactory isn't initializing correctly.

Tried with pnpjs (latest) as well and get the same results so looks to be wider.  Also tried with SPFx 1.14.0 and no difference

**Comment by dcashpeterson** [comment]
@jimmyalfSoleil @techienickb  is this ok to close.

**Comment by techienickb** [comment]
I think so. It was a spfx issue that looks to have been fixed niw

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dcashpeterson** [comment]
Closed fixed in https://github.com/SharePoint/sp-dev-docs/issues/7963
