### ISSUE TITLE
videoCard: media element in adaptive card doesn't show up in the mobile version of Viva Connections

### ISSUE THREAD

**Issue by giuleon** [pnp/sp-dev-fx-aces#57]
## Sample
I'm referring to the following sample:
https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/ace-cardgallery/src/adaptiveCardExtensions/videocard

## Expected or Desired Behavior

The media element should be available in teams mobile as well

## Observed Behavior
I'm wondering if the media element (adaptive card) is supported in Teams mobile viva connections.
It works fine in Teams desktop/web version.

## Steps to Reproduce

1. Deploy the sample in the SP App Catalog
2. Install the SPFx in the Home Site
3. Add the adaptive card in the Viva Connection Dashboard
4. Open Teams Viva Connections from a smartphone

**Comment by anoopt** [comment]
Adding a link to a [related issue](https://github.com/SharePoint/sp-dev-docs/issues/7808).

**Comment by dcashpeterson** [comment]
@anoopt  you beat me to it.

**Comment by TheRealBenForce** [comment]
I'm experiencing this as well.
Also, I have found that VIva Connections Card Designer action "Display a specified or current location" does not work on mobile, but I'm not sure where to open the issue. Tested with a specified location on both a Pixel and iPhone. Any suggestions or just piggy back on this one @dcashpeterson ?

**Comment by dcashpeterson** [comment]
@TheRealBenForce The best place to report any bugs with SPFx is the SPFx Developer Docs repo. https://github.com/SharePoint/sp-dev-docs

As @anoopt mentioned the issue with the Video Card is already reported. If you are having an issue with mobile support for the Current Location I would post it there as well.
