### ISSUE TITLE
Hide cardview in init method

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/sp-dev-fx-aces#94]
is it possible to hide cardview i.e hide the entire card based on a condition ?

**Comment by dcashpeterson** [comment]
@harshdamaniahd You can do that. There are two ways to handle it. 1) you can use audience targeting. Put the users that can see the ACE in a group and the only show it to them. This is set in the properties pane. 2) You can set the isVisible property on the card in the init method. There is an example here. https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/ImageCard-HideACE/src/adaptiveCardExtensions/hideAce

**Comment by harshdamaniahd** [comment]
Hey thanks @dcashpeterson  , i tried the isVisible property, but the card always loads
![image](https://user-images.githubusercontent.com/11780473/183894976-165a94ac-88a0-4b46-aa7d-fa8ee0a88539.png)

So what i want to do is that, if a user profile property is not updated the show card , else do not show card. So i was testing isVisible property, but it doesnt work.

Should i test it by deploying it ?

**Comment by dcashpeterson** [comment]
@harshdamaniahd as I said, you need to do it in the init method. Look at the example. It works off of local storage but you can substitute your user profile code there.

**Comment by harshdamaniahd** [comment]
Yes i have written it in init method only 
  public onInit(): Promise<void> {
    
    this.state = { };
    debugger;
    
   this.isVisible=false;
   
   this.cardNavigator.register(CARD_VIEW_REGISTRY_ID, () => new CardView());
    this.quickViewNavigator.register(QUICK_VIEW_REGISTRY_ID, () => new QuickView());
  

    return Promise.resolve();
  } @dcashpeterson

**Comment by dcashpeterson** [comment]
@harshdamaniahd I can't speak for the rest of your code but I just tried a new ACE using 1.15.2 and the code you posted works just fine and hides the ACE. I am guessing that it is something else other than the isVisible property and that the init is erroring out before it gets to that line.

**Comment by harshdamaniahd** [comment]
Hi , it works after deploying , doesnt work on workbench for me
