### ISSUE TITLE
Displaying blob url in teams mobile client doesnt work

### ISSUE THREAD

**Issue by harshdamaniahd** [pnp/sp-dev-fx-aces#96]
Hi, I am fetching User Profile photo from ms graph
```
 const client: MSGraphClient = await this.context.msGraphClientFactory
        .getClient("3")
        .then();
      var userPhoto:any = await client
        .api("me/photos/360x360/$value")
        .responseType("blob").get()
    
      let userPhotoBlob: any = URL.createObjectURL(userPhoto).toString();
```

and i am trying to display this photo on  adaptive card view with image , marked yellow . are there any ways to achieve this
![image](https://user-images.githubusercontent.com/11780473/184360597-dedf2218-ddd3-4ed5-93a0-afd404c3611f.png)

**Comment by dcashpeterson** [comment]
@harshdamaniahd you need to set the primary image url with the value you get back from the graph. One note thought, this repo is for issues related to the different ACE samples. If you are having issues getting your code to work the best place to post would be [SP-Dev-Docs](https://github.com/SharePoint/sp-dev-docs/issues). That repo has a lot more eyes on it.

**Comment by harshdamaniahd** [comment]
Thanks @dcashpeterson but the url we get is a blob url and it is not supportted in adaptive card

**Comment by dcashpeterson** [comment]
@harshdamaniahd you can convert a blob to base64 which is supported but again, if you want specific help SP-Dev-Docs is the best place to ask.
